---
- name: Apache
  hosts: all
  tasks:
    - name: Instalar para Debian
      apt: 
        name: apache2
        state: present
      when: ansible_os_family == 'Debian' 

    - name: Instalar para RHEL
      yum:
        name: httpd
        state: present
      when: ansible_os_family == 'RedHat'

    - name: Copiando o index 
      copy:
        src: index.html
        dest: /var/www/html/index.html

    - name: Reiniciar o apache
      service:
        name: apache2
        state: restarted
      when: ansible_os_family == 'Debian'

    - name: Reiniciar o apache RHEL
      service:
        name: httpd
        state: restarted
      when: ansible_os_family == 'RedHat'

...
